### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by ghost** [Sarrus1/FaceitLevels-for-kento-RankMe#1]
Hello, man I have the Kento-RankMe working well, but when I try to run your plugin I got the following error:

L 02/11/2021 - 14:39:59: [SM] Unable to load plugin "FaceitLevels-kento-rankme.smx": Could not find required plugin "levelsranks"

EDIT: After I removed the #include of "lvl-ranks" doesnt give me that error, but now doesnt show me any image!

Like the bandadge or medal that player has, desapear, but doesnt show the rank! The spot stays empty

**Comment by Sarrus1** [comment]
Hey, thanks for letting me know.

Please make sure you use the latest release and not the version in the master branch.
You can get it [here](https://github.com/Sarrus1/FaceitLevels-for-kento-RankMe/releases/tag/v1.0)

This should fix your issue
