### ISSUE TITLE
RankMe_IsPlayerLoaded

### ISSUE THREAD

**Issue by EmileIssarov** [Sarrus1/FaceitLevels-for-kento-RankMe#3]
![image](https://user-images.githubusercontent.com/92203995/153706861-dd540f28-c065-4073-ac10-c2787c6ebfac.png)
I have this exact issue, all points that you indicated in the instructions are installed. What is the problem?

**Comment by Sarrus1** [comment]
You need to update your rankme plugin. Latest version is 0.33.

**Comment by Sarrus1** [comment]
Hopefully fixed in v1.2.0.
Please reopen if it's not.
